on:
  workflow_call:
    inputs:
      SERVICE:
        type: string
        required: true
    secrets:
      GCP_CREDS:
        required: true
      SLACK_WEBHOOK:
        required: true
      GH_TOKEN:
        required: true

env:
  REGISTRY: asia-southeast1-docker.pkg.dev
  IMAGE: "${REGISTRY}/cloudverse-foundation/cloudverse/${{ inputs.SERVICE }}"

jobs:
  InitInfo:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      environment: ${{ steps.environment.outputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        run: echo "version=`git describe --tags`" >> $GITHUB_OUTPUT
      - id: environment
        run: |
          [[ $GITHUB_REF_NAME == "dev" ]] && echo "environment=dev" >> $GITHUB_OUTPUT
          [[ $GITHUB_REF_NAME == "test" ]] && echo "environment=test" >> $GITHUB_OUTPUT
          [[ $GITHUB_REF_NAME == "production" ]] && echo "environment=staging" >> $GITHUB_OUTPUT

  Build:
    runs-on: ubuntu-latest
    needs: InitInfo
    outputs:
      version: ${{ steps.setversion.outputs.version }}
    steps:
      - name: Slack notify start build
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: cloudverse-devops
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "`${{ inputs.SERVICE }}` start build on `${{ needs.InitInfo.outputs.environment }}`"
          SLACK_MESSAGE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
      - name: Log in to the Container registry
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker container
        env:
          version: ${{ needs.InitInfo.outputs.version }}
        run: |
          docker buildx build -t ${IMAGE}:${version} .
          docker push ${IMAGE}:${version}
      - name: Slack Notification Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: cloudverse-devops
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "`${{ inputs.SERVICE }}` built `success` on `${{ needs.InitInfo.outputs.environment }}`"
          SLACK_MESSAGE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Slack Notification Success
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: cloudverse-devops
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "`${{ inputs.SERVICE }}` built `failed` on `${{ needs.InitInfo.outputs.environment }}`"
          SLACK_MESSAGE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    env:
      version: ${{ needs.InitInfo.outputs.version }}
      environment: ${{ needs.InitInfo.outputs.environment }}
      service: ${{ inputs.servie }}
      token: ${{ secrets.GH_TOKEN }}
    if: github.ref_name == 'dev' || github.ref_name == 'staging' || github.ref_name == 'production'
    steps:
      - run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer '${token}'" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/CloudVerse-Pte-Ltd/argocd/actions/workflows/83931042/dispatches \
          -d '{"ref":"main","inputs":{"environment":"'${environment}'","service":"'${service}'","version": "'${version}'"}}'
      - name: Slack Notification Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: cloudverse-devops
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "`${{ inputs.SERVICE }}` deployed `success` on `${{ needs.InitInfo.outputs.environment }}`"
          SLACK_MESSAGE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Slack Notification Success
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: cloudverse-devops
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "`${{ inputs.SERVICE }}` deployed `failed` on `${{ needs.InitInfo.outputs.environment }}`"
          SLACK_MESSAGE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
